x-airflow-common: &airflow-common
    build:
        context: .
        dockerfile: Dockerfile
        args:
            AIRFLOW_IMAGE_NAME: ${AIRFLOW_IMAGE_NAME:-apache/airflow:3.1.3}
    env_file:
        - ${ENV_FILE_PATH:-.env}
    environment: &airflow-common-env
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
        # OPTIMASI RAM: Batasi jumlah proses
        AIRFLOW__CORE__PARALLELISM: "2"
        AIRFLOW__CORE__DAG_CONCURRENCY: "1"
        AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: "1"
        AIRFLOW__SCHEDULER__PARSING_PROCESSES: "1"
        AIRFLOW__SCHEDULER__MAX_THREADS: "1"
        # GABUNGKAN DAG PROCESSOR KE SCHEDULER
        AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: "false" 
        AIRFLOW__CORE__LOAD_EXAMPLES: "false"
        AIRFLOW_CONFIG: "/opt/airflow/config/airflow.cfg"
        GOOGLE_APPLICATION_CREDENTIALS: "/opt/airflow/keys/key.json"
        GCP_PROJECT_ID: ${GCP_PROJECT_ID}

    volumes:
        - ./dags:/opt/airflow/dags
        - ./logs:/opt/airflow/logs
        - ./config:/opt/airflow/config
        - ./plugins:/opt/airflow/plugins
        - ./keys:/opt/airflow/keys:ro
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on: &airflow-common-depends-on
        postgres:
            condition: service_healthy

services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "airflow"]
            interval: 10s
            retries: 5
        restart: always

    airflow-webserver: # Di AF3 bisa disebut API Server + UI
        <<: *airflow-common
        command: webserver # Gunakan webserver untuk bundle UI
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            airflow-init:
                condition: service_completed_successfully

    airflow-scheduler:
        <<: *airflow-common
        command: scheduler
        healthcheck:
            test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
            interval: 30s
            timeout: 10s
            retries: 5
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            airflow-init:
                condition: service_completed_successfully

    airflow-init:
        <<: *airflow-common
        entrypoint: /bin/bash
        command:
            - -c
            - |
                mkdir -p /opt/airflow/{logs,dags,plugins,config}
                airflow db migrate
                airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin
        environment:
            <<: *airflow-common-env
            _AIRFLOW_DB_MIGRATE: "true"
        user: "0:0"

volumes:
    postgres-db-volume: