FROM apache/superset:4.0.0
USER root

COPY requirements-superset.txt .
RUN pip install --no-cache-dir -r requirements-superset.txt

COPY init-superset.sh /app/init-superset.sh
RUN chmod +x /app/init-superset.sh

USER superset