version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    # Optimasi RAM (Penting untuk LocalExecutor)
    AIRFLOW__CORE__PARALLELISM: 2
    AIRFLOW__CORE__DAG_CONCURRENCY: 1
    # Memastikan python menemukan modul lokal Anda
    PYTHONPATH: /opt/airflow:/opt/airflow/dags
    # Force DAG parsing & discovery
    AIRFLOW__CORE__DAG_DISCOVERY_SAFE_MODE: 'false'
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: 'false'
    AIRFLOW__WEBSERVER__AUTHENTICATE: 'False'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.default'

  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - ~/.aws:/home/airflow/.aws:ro
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-airflow}"]
      interval: 10s
      retries: 5
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    user: "0:0" # Gunakan root hanya untuk inisialisasi folder jika perlu
    command:
      - bash
      - -c
      - |
        # Buat folder jika belum ada dengan permission yang benar
        mkdir -p /opt/airflow/{logs,dags,plugins,config}
        
        # Jalankan sebagai user airflow (50000)
        su -s /bin/bash airflow -c "airflow db migrate && \
        airflow users create \
          --username admin \
          --firstname admin \
          --lastname admin \
          --role Admin \
          --email admin@example.com \
          --password admin || true"

volumes:
  postgres-db-volume: